### ISSUE TITLE
对.net Core的支持

### ISSUE THREAD

**Issue by liangxiao1714** [itdos/Dos.ORM#10]
Dos.ORM用起来感觉很不错，但是现在还不支持.Net Core这种跨平台的SDK，希望能加入对.Net Core的支持以便于项目的跨平台使用和部署...

**Comment by itdos** [comment]
我们会尽快支持，谢谢。大概2、3个月后吧。

**Comment by liangxiao1714** [comment]
感谢回复，期待后续版本，结贴...

**Comment by terrydash** [comment]
太好了 之前的项目就是用的DOS.ORM
